app_images:
- appImageId: 90f46e9dee9f422ab85227881c5ed242
  flavourName: vanilla
  image:
    buildAt: '2025-05-14T16:57:34.865875'
    imageString: jhnnsrs/ome:0.1.6-vanilla
  inspection:
    implementations:
    - definition:
        args:
        - assignWidget:
            kind: SEARCH
            query: "query SearchFiles($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: files(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          effects: []
          identifier: '@mikro/file'
          key: file
          kind: STRUCTURE
          label: file
          nullable: false
          validators: []
        - assignWidget:
            kind: SEARCH
            query: "query SearchDatasets($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: datasets(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          effects: []
          identifier: '@mikro/dataset'
          key: dataset
          kind: STRUCTURE
          label: dataset
          nullable: true
          validators: []
        - assignWidget:
            kind: SEARCH
            query: "query SearchStages($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: stages(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          effects: []
          identifier: '@mikro/stage'
          key: stage
          kind: STRUCTURE
          label: stage
          nullable: true
          validators: []
        - default: true
          description: Whether to create a position from the first planes (only if
            stage is provided). Defaults to True.
          effects: []
          key: position_from_planes
          kind: BOOL
          label: position_from_planes
          nullable: true
          validators: []
        - default: true
          description: Whether to create a timepoint from the first time (only if
            era is provided). Defaults to True.
          effects: []
          key: timepoint_from_time
          kind: BOOL
          label: timepoint_from_time
          nullable: true
          validators: []
        - default: true
          description: Whether to create a channel from the channels. Defaults to
            True.
          effects: []
          key: channels_from_channels
          kind: BOOL
          label: channels_from_channels
          nullable: true
          validators: []
        - description: The tolerance for the position. Defaults to no tolerance.
          effects: []
          key: position_tolerance
          kind: FLOAT
          label: position_tolerance
          nullable: true
          validators: []
        - description: The tolerance for the timepoint. Defaults  to no tolerance.
          effects: []
          key: timepoint_tolerance
          kind: FLOAT
          label: timepoint_tolerance
          nullable: true
          validators: []
        collections: []
        description: Converts an Omero File in a set of Mikrodata
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        logo: ome.png
        name: Convert Omero
        portGroups: []
        returns:
        - children:
          - assignWidget:
              kind: SEARCH
              query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
                \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
                \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
                \    __typename\n  }\n}"
              ward: mikro
            effects: []
            identifier: '@mikro/image'
            key: '...'
            kind: STRUCTURE
            nullable: false
            validators: []
          description: The created series in this file
          effects: []
          key: return0
          kind: LIST
          label: return0
          nullable: false
          validators: []
        stateful: false
      dependencies: []
      dynamic: false
      interface: convert_omero_file
      logo: ome.png
    - definition:
        args:
        - assignWidget:
            kind: SEARCH
            query: "query SearchFiles($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: files(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          effects: []
          identifier: '@mikro/file'
          key: file
          kind: STRUCTURE
          label: file
          nullable: false
          validators: []
        - assignWidget:
            kind: SEARCH
            query: "query SearchDatasets($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: datasets(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          effects: []
          identifier: '@mikro/dataset'
          key: dataset
          kind: STRUCTURE
          label: dataset
          nullable: true
          validators: []
        collections: []
        description: Converts an tilffe File in a set of Mikrodata (without metadata)
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        name: Convert Tiff File
        portGroups: []
        returns:
        - children:
          - assignWidget:
              kind: SEARCH
              query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
                \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
                \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
                \    __typename\n  }\n}"
              ward: mikro
            effects: []
            identifier: '@mikro/image'
            key: '...'
            kind: STRUCTURE
            nullable: false
            validators: []
          description: The created series in this file
          effects: []
          key: return0
          kind: LIST
          label: return0
          nullable: false
          validators: []
        stateful: false
      dependencies: []
      dynamic: false
      interface: convert_tiff_file
    - definition:
        args:
        - assignWidget:
            kind: SEARCH
            query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
              \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
              \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
              \    __typename\n  }\n}"
            ward: mikro
          effects: []
          identifier: '@mikro/image'
          key: image
          kind: STRUCTURE
          nullable: false
          validators: []
        collections: []
        description: No Description
        interfaces: []
        isDev: true
        isTestFor: []
        kind: FUNCTION
        name: Multi Scale
        portGroups: []
        returns:
        - children:
          - assignWidget:
              kind: SEARCH
              query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
                \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
                \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
                \    __typename\n  }\n}"
              ward: mikro
            effects: []
            identifier: '@mikro/image'
            key: '...'
            kind: STRUCTURE
            nullable: false
            validators: []
          effects: []
          key: return0
          kind: LIST
          nullable: false
          validators: []
        stateful: false
      dependencies: []
      dynamic: false
      interface: multi_scale
    requirements:
    - description: An instance of ArkitektNext Datalayer to make requests to the user's
        data
      key: datalayer
      optional: true
      service: live.arkitekt.s3
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: lok
      optional: false
      service: live.arkitekt.lok
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: true
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    size: 1559127213
  manifest:
    author: jhnnsrs
    entrypoint: app
    identifier: ome
    scopes:
    - read
    version: 0.1.6
  selectors: []
latest_app_image: 90f46e9dee9f422ab85227881c5ed242
