app_images:
- appImageId: ed82684dd36a4302983ac104269d5d76
  flavourName: vanilla
  image:
    buildAt: '2026-06-30T08:46:32.300091'
    imageString: jhnnsrs/ome:0.4.0-vanilla
  inspection:
    bloks: []
    implementations:
    - definition:
        args:
        - effects: []
          identifier: '@mikro/file'
          key: file
          kind: STRUCTURE
          nullable: false
          validators: []
          widget:
            kind: SEARCH
            query: "query SearchFiles($search: String, $values: [ID!], $limit: Int,\
              \ $offset: Int = 0) {\n  options: files(\n    filters: {search: $search,\
              \ ids: $values}\n    pagination: {limit: $limit, offset: $offset}\n\
              \  ) {\n    value: id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
        - effects: []
          identifier: '@mikro/stage'
          key: stage
          kind: STRUCTURE
          nullable: true
          validators: []
          widget:
            kind: SEARCH
            query: "query SearchStages($search: String, $values: [ID!], $limit: Int,\
              \ $offset: Int = 0) {\n  options: stages(\n    filters: {search: $search,\
              \ ids: $values}\n    pagination: {limit: $limit, offset: $offset}\n\
              \  ) {\n    value: id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
        collections: []
        description: No Description
        interfaces: []
        isDev: true
        isTestFor: []
        key: convert_omero_file
        kind: GENERATOR
        logo: ome.png
        name: Convert Omero File
        portGroups: []
        returns:
        - effects: []
          identifier: '@mikro/image'
          key: return0
          kind: STRUCTURE
          nullable: false
          validators: []
        stateful: false
        version: '1'
      dependencies: []
      dynamic: false
      interface: convert_omero_file
      locks: []
      logo: ome.png
      manipulates: []
      needsToken: true
      optimistics: []
      tracks: []
    locks: []
    requirements:
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: false
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: s3
      optional: false
      service: live.arkitekt.s3
    size: 1669800779
    states: []
  manifest:
    author: jhnnsrs
    identifier: ome
    scopes:
    - read
    version: 0.4.0
  selectors: []
latest_app_image: ed82684dd36a4302983ac104269d5d76
