app_images:
- appImageId: da60d36f7c1d48e69136699f4fcc901e
  flavourName: vanilla
  image:
    buildAt: '2025-08-22T17:55:39.019884'
    imageString: jhnnsrs/ome:0.1.9-vanilla
  inspection:
    implementations:
    - definition:
        args:
        - assignWidget:
            kind: SEARCH
            query: "query SearchFiles($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: files(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          description: The File to be converted
          effects: []
          identifier: '@mikro/file'
          key: file
          kind: STRUCTURE
          label: file
          nullable: false
          validators: []
        - assignWidget:
            kind: SEARCH
            query: "query SearchStages($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: stages(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          description: The Stage in which to put the Image. Defaults to None.
          effects: []
          identifier: '@mikro/stage'
          key: stage
          kind: STRUCTURE
          label: stage
          nullable: true
          validators: []
        collections: []
        description: Converts an Omero File in a set of Mikrodata
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        logo: ome.png
        name: Convert Omero
        portGroups: []
        returns:
        - children:
          - assignWidget:
              kind: SEARCH
              query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
                \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
                \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
                \    __typename\n  }\n}"
              ward: mikro
            effects: []
            identifier: '@mikro/image'
            key: '...'
            kind: STRUCTURE
            nullable: false
            validators: []
          description: The created series in this file
          effects: []
          key: return0
          kind: LIST
          label: return0
          nullable: false
          validators: []
        stateful: false
      dependencies: []
      dynamic: false
      interface: convert_omero_file
      logo: ome.png
    requirements:
    - description: An instance of ArkitektNext Datalayer to make requests to the user's
        data
      key: datalayer
      optional: true
      service: live.arkitekt.s3
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: lok
      optional: false
      service: live.arkitekt.lok
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: true
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    size: 1482598149
  manifest:
    author: jhnnsrs
    entrypoint: app
    identifier: ome
    scopes:
    - read
    version: 0.1.9
  selectors: []
- appImageId: 27a1ef39ed374202873dce97b74a4279
  flavourName: vanilla
  image:
    buildAt: '2025-09-19T09:10:46.688098'
    imageString: jhnnsrs/ome:0.2.0-vanilla
  inspection:
    implementations:
    - definition:
        args:
        - assignWidget:
            kind: SEARCH
            query: "query SearchFiles($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: files(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          description: The File to be converted
          effects: []
          identifier: '@mikro/file'
          key: file
          kind: STRUCTURE
          label: file
          nullable: false
          validators: []
        - assignWidget:
            kind: SEARCH
            query: "query SearchStages($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: stages(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          description: The Stage in which to put the Image. Defaults to None.
          effects: []
          identifier: '@mikro/stage'
          key: stage
          kind: STRUCTURE
          label: stage
          nullable: true
          validators: []
        collections: []
        description: Converts an Omero File in a set of Mikrodata
        interfaces: []
        isDev: false
        isTestFor: []
        kind: FUNCTION
        logo: ome.png
        name: Convert Omero
        portGroups: []
        returns:
        - children:
          - assignWidget:
              kind: SEARCH
              query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
                \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
                \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
                \    __typename\n  }\n}"
              ward: mikro
            effects: []
            identifier: '@mikro/image'
            key: '...'
            kind: STRUCTURE
            nullable: false
            validators: []
          description: The created series in this file
          effects: []
          key: return0
          kind: LIST
          label: return0
          nullable: false
          validators: []
        stateful: false
      dependencies: []
      dynamic: false
      interface: convert_omero_file
      logo: ome.png
    requirements:
    - description: An instance of ArkitektNext Datalayer to make requests to the user's
        data
      key: datalayer
      optional: true
      service: live.arkitekt.s3
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: lok
      optional: false
      service: live.arkitekt.lok
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: true
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    size: 1662005942
  manifest:
    author: jhnnsrs
    entrypoint: app
    identifier: ome
    scopes:
    - read
    version: 0.2.0
  selectors: []
- appImageId: ae44f4f78b5c476cb714d6d91e09f16e
  flavourName: vanilla
  image:
    buildAt: '2025-09-19T09:17:00.819502'
    imageString: jhnnsrs/ome:0.3.0-vanilla
  inspection:
    implementations:
    - definition:
        args:
        - assignWidget:
            kind: SEARCH
            query: "query SearchFiles($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: files(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          description: The File to be converted
          effects: []
          identifier: '@mikro/file'
          key: file
          kind: STRUCTURE
          label: file
          nullable: false
          validators: []
        - assignWidget:
            kind: SEARCH
            query: "query SearchStages($search: String, $values: [ID!], $pagination:\
              \ OffsetPaginationInput) {\n  options: stages(\n    filters: {search:\
              \ $search, ids: $values}\n    pagination: $pagination\n  ) {\n    value:\
              \ id\n    label: name\n    __typename\n  }\n}"
            ward: mikro
          description: The Stage in which to put the Image. Defaults to None.
          effects: []
          identifier: '@mikro/stage'
          key: stage
          kind: STRUCTURE
          label: stage
          nullable: true
          validators: []
        collections: []
        description: Converts an Omero File in a set of Mikrodata
        interfaces: []
        isDev: false
        isTestFor: []
        kind: GENERATOR
        logo: ome.png
        name: Convert Omero
        portGroups: []
        returns:
        - assignWidget:
            kind: SEARCH
            query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
              \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
              \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
              \    __typename\n  }\n}"
            ward: mikro
          description: The created series in this file
          effects: []
          identifier: '@mikro/image'
          key: return0
          kind: STRUCTURE
          label: return0
          nullable: false
          validators: []
        stateful: false
      dependencies: []
      dynamic: false
      interface: convert_omero_file
      logo: ome.png
    requirements:
    - description: An instance of ArkitektNext Datalayer to make requests to the user's
        data
      key: datalayer
      optional: true
      service: live.arkitekt.s3
    - description: An instance of ArkitektNext Lok to authenticate the user
      key: lok
      optional: false
      service: live.arkitekt.lok
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: true
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    size: 1662149210
  manifest:
    author: jhnnsrs
    entrypoint: app
    identifier: ome
    scopes:
    - read
    version: 0.3.0
  selectors: []
latest_app_image: ae44f4f78b5c476cb714d6d91e09f16e
